version: '3.0'
services:
  db:
    image: mysql:8.0
    platform: linux/x86_64  # M1 Macの場合必要
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # rootアカウントをパスワードなしで作成
      MYSQL_DATABASE: 'circle_development'  # 初期データベースとしてdemoを設定
      TZ: 'Asia/Tokyo'  # タイムゾーンを日本時間に設定
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    ports:
      - 3306:3306  # ホスト
    # networks:
    #   - my_network
  api:
    container_name: "api"
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      # - 8000:8000
    # networks:
    #   - my_network
  redis:
    container_name: "redis"
    image: redis
    ports:
      # - "127.0.0.1:6379:6379"
      - "6379:6379"
    # networks:
    #   - my_network
# networks:
#   my_network:
volumes:
  mysql_data:
    # driver: local