"""change type for uid from user

Revision ID: 1b0e4b3cd367
Revises: 8c4206335074
Create Date: 2022-12-28 05:11:40.158324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0e4b3cd367'
down_revision = '8c4206335074'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uid', 
        existing_type=sa.Integer,
        type_=sa.String(768)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uid', 
        existing_type=sa.Text,
        type_=sa.String(768)
    )
    # ### end Alembic commands ###
