"""AddColumnToAuthorityforGroupUsers

Revision ID: 41d8b75b5b75
Revises: 65bd277dd471
Create Date: 2023-04-03 04:03:04.747814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d8b75b5b75'
down_revision = '65bd277dd471'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_users', sa.Column('authority', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_users', 'authority')
    # ### end Alembic commands ###
