"""AddColumnToNameforGroup

Revision ID: 65bd277dd471
Revises: bf293cdad293
Create Date: 2023-04-03 03:43:30.143579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65bd277dd471'
down_revision = 'bf293cdad293'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('name', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_column('groups', 'name')
    # ### end Alembic commands ###
