"""Added columnsDeviceToken For User

Revision ID: 74fae73b8413
Revises: b3d9ffd67d77
Create Date: 2023-06-08 07:57:57.592464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fae73b8413'
down_revision = 'b3d9ffd67d77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_token', sa.String(length=768), nullable=False))
    op.create_unique_constraint(None, 'users', ['device_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'device_token')
    # ### end Alembic commands ###
