"""UserTableAddColumFirstTime

Revision ID: 8c4206335074
Revises: 198792cdd13a
Create Date: 2022-12-24 23:14:19.872174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4206335074'
down_revision = '198792cdd13a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_time', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_time')
    # ### end Alembic commands ###
