"""Added columns2.

Revision ID: 8ca493d2c15d
Revises: 47800f214bca
Create Date: 2022-12-24 17:49:12.650079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca493d2c15d'
down_revision = '47800f214bca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title3', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'title3')
    # ### end Alembic commands ###
