"""deleteColumnToIdforGroupUser

Revision ID: 920978b45423
Revises: 41d8b75b5b75
Create Date: 2023-04-05 17:41:59.349622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '920978b45423'
down_revision = '41d8b75b5b75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_group_users_id', table_name='group_users')
    op.drop_column('group_users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_users', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_group_users_id', 'group_users', ['id'], unique=False)
    # ### end Alembic commands ###
