"""Added columns.

Revision ID: 996d4471e2e7
Revises: baa2f13de2cb
Create Date: 2024-01-15 16:18:47.417333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996d4471e2e7'
down_revision = 'baa2f13de2cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('description', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'description')
    # ### end Alembic commands ###
