"""AddColumnsForGroupChatUpdate

Revision ID: b5c98bdcccff
Revises: b3d9ffd67d77
Create Date: 2023-06-30 04:42:52.976305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c98bdcccff'
down_revision = 'b3d9ffd67d77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_chats', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_chats', 'created_at')
    # ### end Alembic commands ###
